# Generated by Django 2.0.1 on 2018-01-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20180126_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='steps',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='no',
            field=models.CharField(max_length=100),
        ),
    ]
